[alias]
b = "build --all"
br = "build --release --all"
accu-check = "run --release --package accu-check"

[build]
target = "armv7-unknown-linux-musleabihf"

[target.armv7-unknown-linux-musleabihf]
linker = "clang"
rustflags = [
    "-C", "link-arg=--target=arm-linux-musleabihf",
    "-C", "link-arg=-fuse-ld=lld",

    "-C", "target-cpu=cortex-a9"
]