[alias]
b = "build --all"
br = "build --release --all"
r = "run"
rr = "run --release"
accu-check = "run --release --bin accu-check"

#[build]
#target = "armv7-unknown-linux-musleabihf"
#
#[target.armv7-unknown-linux-musleabihf]
#linker = "arm-linux-gnueabihf-gcc"
#rustflags = [
#    "-C", "target-cpu=cortex-a9",
#    "-C", "link-arg=-static"
#]