# TCL File Generated by Component Editor 25.1
# Tue Apr 07 15:45:13 IST 2026
# DO NOT MODIFY


# 
# vfp8_controller "vfp8_controller" v1.0
#  2026.04.07.15:45:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vfp8_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME vfp8_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vfp8_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller.v VERILOG PATH controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock a_clk clk Input 1


# 
# connection point trx_interface
# 
add_interface trx_interface avalon end
set_interface_property trx_interface addressUnits WORDS
set_interface_property trx_interface associatedClock clock
set_interface_property trx_interface associatedReset reset
set_interface_property trx_interface bitsPerSymbol 8
set_interface_property trx_interface burstOnBurstBoundariesOnly false
set_interface_property trx_interface burstcountUnits WORDS
set_interface_property trx_interface explicitAddressSpan 0
set_interface_property trx_interface holdTime 0
set_interface_property trx_interface linewrapBursts false
set_interface_property trx_interface maximumPendingReadTransactions 0
set_interface_property trx_interface maximumPendingWriteTransactions 0
set_interface_property trx_interface readLatency 0
set_interface_property trx_interface readWaitTime 1
set_interface_property trx_interface setupTime 0
set_interface_property trx_interface timingUnits Cycles
set_interface_property trx_interface writeWaitTime 0
set_interface_property trx_interface ENABLED true
set_interface_property trx_interface EXPORT_OF ""
set_interface_property trx_interface PORT_NAME_MAP ""
set_interface_property trx_interface CMSIS_SVD_VARIABLES ""
set_interface_property trx_interface SVD_ADDRESS_GROUP ""

add_interface_port trx_interface write write Input 1
add_interface_port trx_interface writedata writedata Input 128
add_interface_port trx_interface read read Input 1
add_interface_port trx_interface readdata readdata Output 128
set_interface_assignment trx_interface embeddedsw.configuration.isFlash 0
set_interface_assignment trx_interface embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment trx_interface embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment trx_interface embeddedsw.configuration.isPrintableDevice 0

